[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`four_color` is a package for Four Color Problem."
homepage = "https://github.com/SaitoTsutomu/four_color"
license = "Apache-2.0"
name = "four_color"
readme = "README.rst"
version = "0.2.0"

[tool.poetry.dependencies]
flask = "^2.3.2"
networkx = "^3.1"
pillow = "^9.5.0"
pulp = "^2.7.0"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.2.0"
pytest = "^7.3.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
